include::introduction.adoc[]

IMPORTANT: This quickstart can run in 2 modes: standalone on your machine and on Kubernetes / OpenShift Cluster

include::introduction-other.adoc[]
== Deployment options

You can run this quickstart in the following modes:

* Kubernetes / Single-node OpenShift cluster
* Standalone on your machine

The most effective way to run this quickstart is to deploy and run the project on OpenShift.

For more details about running this quickstart on a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

== Running the Quickstart on a single-node Kubernetes/OpenShift cluster

IMPORTANT: You need to run this example on Container Development Kit 3.3 or OpenShift 3.7.
Both of these products have suitable Fuse images pre-installed.
If you run it in an environment where those images are not preinstalled follow the steps described in <<single-node-without-preinstalled-images>>.

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/${project.artifactId}`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/${project.artifactId}
----
include::oc-special-configuration.adoc[]
include::oc-deploy.adoc[]
include::validation.adoc[]
include::validation-see-log.adoc[]

[#single-node-without-preinstalled-images]
=== Running the Quickstart on a single-node Kubernetes/OpenShift cluster without preinstalled images

A single-node Kubernetes/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetes/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.


. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Configure Red Hat Container Registry authentication (if it is not configured).
Follow https://access.redhat.com/documentation/en-us/red_hat_fuse/7.9/html-single/fuse_on_openshift_guide/index#configure-container-registry[documentation].

. Import base images in your newly created project (MY_PROJECT_NAME). :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc import-image fuse-java-openshift:1.9 --from=registry.redhat.io/fuse7/fuse-java-openshift:1.9 --confirm
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/${project.artifactId}`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/${project.artifactId}
----
include::oc-special-configuration.adoc[]
include::oc-deploy-without-images.adoc[]
include::validation.adoc[]
include::validation-see-log.adoc[]
include::validation-summary.adoc[]
include::integration-testing.adoc[]

== Running the quickstart standalone on your machine

To run this quickstart as a standalone project on your local machine:
include::local-configuration.adoc[]

. Download the project and extract the archive on your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. Run the service:

+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn spring-boot:run
----
include::validation-local.adoc[]

---

Generated by maven plugin - do NOT edit this file!