[=introduction]

IMPORTANT: This quickstart can run in 1 mode: on Kubernetese / OpenShift Cluster

[#if introductionOther??][=introductionOther][/#if]

== Running the Quickstart on a single-node Kubernetese/OpenShift cluster

IMPORTANT: You need to run this example on Container Development Kit 3.3 or OpenShift 3.7.
Both of these products have suitable Fuse images pre-installed.
If you run it in an environment where those images are not preinstalled follow the steps described in <<single-node-without-preinstalled-images>>.

A single-node Kubernetese/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetese/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/[=project.artifactId]`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/[=project.artifactId]
----

[#if ocSpecialConfiguration??][=ocSpecialConfiguration][/#if]

[#if ocDeploy??][=ocDeploy][#else]
. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests oc:deploy -Popenshift
----
[/#if]

[#if validation??][=validation][#else]
. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `[=project.artifactId]` has started up.
[/#if]

[#if validationSeeLog??]
[=validationSeeLog]
[#else]
. On the project's `Overview` page, navigate to the details page deployment of the `[=project.artifactId]` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/rc/[=project.artifactId]-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the messages sent by Camel.
[/#if]

[[#lt]#single-node-without-preinstalled-images]
=== Running the Quickstart on a single-node Kubernetese/OpenShift cluster without preinstalled images

A single-node Kubernetese/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetese/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.


. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Import base images in your newly created project (MY_PROJECT_NAME) according to https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/html/fuse_on_openshift_guide/get-started-non-admin[documentation].

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/[=project.artifactId]`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/[=project.artifactId]
----

[#if ocSpecialConfiguration??][=ocSpecialConfiguration][/#if]

[#if ocDeployWithoutImages??][=ocDeployWithoutImages][#else]
. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests oc:deploy -Popenshift -Djkube.generator.fromMode=istag -Djkube.generator.from=MY_PROJECT_NAME/fuse-karaf-openshift:1.9
----
[/#if]

[#if validation??][=validation][#else]
. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `[=project.artifactId]` has started up.
[/#if]

[#if validationSeeLog??][=validationSeeLog][#else]
. On the project's `Overview` page, navigate to the details page deployment of the `[=project.artifactId]` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/rc/[=project.artifactId]-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the messages sent by Camel.
[/#if]

[#if validationSummary??][=validationSummary][/#if]

[#if integrationTesting??][=integrationTesting][/#if]


---

Generated by maven plugin - do NOT edit this file! (See https://github.com/jboss-fuse/documentation-template/blob/main/README.md[documentation])