[=introduction]

IMPORTANT: This quickstart can run in 2 modes: standalone on your machine and on Kubernetes / OpenShift Cluster

[#if introductionOther??][=introductionOther][/#if]

== Deployment options

You can run this quickstart in the following modes:

* Kubernetese / Single-node OpenShift cluster
* Standalone on your machine

The most effective way to run this quickstart is to deploy and run the project on OpenShift.

For more details about running this quickstart on a single-node OpenShift cluster, CI/CD deployments, as well as the rest of the runtime, see the link:http://appdev.openshift.io/docs/spring-boot-runtime.html[Spring Boot Runtime Guide].

== Running the Quickstart on a single-node Kubernetese/OpenShift cluster

IMPORTANT: You need to run this example on Container Development Kit 3.3 or OpenShift 3.7.
Both of these products have suitable Fuse images pre-installed.
If you run it in an environment where those images are not preinstalled follow the steps described in <<single-node-without-preinstalled-images>>.

A single-node Kubernetese/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetese/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.

. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/[=project.artifactId]`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/[=project.artifactId]
----

[#if ocSpecialConfiguration??][=ocSpecialConfiguration][/#if]

[#if ocDeploy??][=ocDeploy][#else]
. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests oc:deploy -Popenshift
----
[/#if]

[#if validation??][=validation][#else]
. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `[=project.artifactId]` has started up.
[/#if]

[#if validationSeeLog??]
[=validationSeeLog]
[#else]
. On the project's `Overview` page, navigate to the details page deployment of the `[=project.artifactId]` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/rc/[=project.artifactId]-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the messages sent by Camel.
[/#if]

[[#lt]#single-node-without-preinstalled-images]
=== Running the Quickstart on a single-node Kubernetese/OpenShift cluster without preinstalled images

A single-node Kubernetese/OpenShift cluster provides you with access to a cloud environment that is similar to a production environment.

If you have a single-node Kubernetese/OpenShift cluster, such as Minishift or the Red Hat Container Development Kit, link:http://appdev.openshift.io/docs/minishift-installation.html[installed and running], you can deploy your quickstart there.


. Log in to your OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc login -u developer -p developer
----

. Create a new OpenShift project for the quickstart:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc new-project MY_PROJECT_NAME
----

. Configure Red Hat Container Registry authentication (if it is not configured).
Follow https://access.redhat.com/documentation/en-us/red_hat_fuse/7.9/html-single/fuse_on_openshift_guide/index#configure-container-registry[documentation].

. Import base images in your newly created project (MY_PROJECT_NAME). :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ oc import-image fuse-java-openshift:1.9 --from=registry.redhat.io/fuse7/fuse-java-openshift:1.9 --confirm
----

. Change the directory to the folder that contains the extracted quickstart application (for example, `my_openshift/[=project.artifactId]`) :
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd my_openshift/[=project.artifactId]
----

[#if ocSpecialConfiguration??][=ocSpecialConfiguration][/#if]

[#if ocDeployWithoutImages??][=ocDeployWithoutImages][#else]
. Build and deploy the project to the OpenShift cluster:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn clean -DskipTests oc:deploy -Popenshift -Djkube.generator.fromMode=istag -Djkube.generator.from=MY_PROJECT_NAME/fuse-java-openshift:1.9
----
[/#if]

[#if validation??][=validation][#else]
. In your browser, navigate to the `MY_PROJECT_NAME` project in the OpenShift console.
Wait until you can see that the pod for the `[=project.artifactId]` has started up.
[/#if]

[#if validationSeeLog??][=validationSeeLog][#else]
. On the project's `Overview` page, navigate to the details page deployment of the `[=project.artifactId]` application: `https://OPENSHIFT_IP_ADDR:8443/console/project/MY_PROJECT_NAME/browse/rc/[=project.artifactId]-NUMBER_OF_DEPLOYMENT?tab=details`.

. Switch to tab `Logs` and then see the messages sent by Camel.
[/#if]

[#if validationSummary??][=validationSummary][/#if]

[#if integrationTesting??][=integrationTesting][#else]
== Integration Testing

The example includes a https://github.com/fabric8io/fabric8/tree/master/components/fabric8-arquillian[fabric8 arquillian] Kubernetese Integration Test.
Once the container image has been built and deployed in Kubernetese, the integration test can be run with:

[source,bash,options="nowrap",subs="attributes+"]
----
mvn test -Dtest=*KT
----

The test is disabled by default and has to be enabled using `-Dtest`. https://fabric8.io/guide/testing.html[Integration Testing] and https://fabric8.io/guide/arquillian.html[Fabric8 Arquillian Extension] provide more information on writing full fledged black box integration tests for Kubernetese.
[/#if]

== Running the quickstart standalone on your machine

To run this quickstart as a standalone project on your local machine:
[#if localConfiguration??][=localConfiguration][/#if]

. Download the project and extract the archive on your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. Run the service:

+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn spring-boot:run
----

[#if validationLocal??][=validationLocal][#else]
. See the messages sent by Camel.
[/#if]


---

Generated by maven plugin - do NOT edit this file! (See https://github.com/jboss-fuse/documentation-template/blob/main/README.md[documentation])